create table alert_info (
alert_id integer,
first_name varchar(20),
last_name varchar(30),
age integer,
gender text,
height varchar(10),
weight varchar(10),
hair_color varchar(20),
clothing_description varchar(240),
medical_issues varchar(240),
medications varchar(240),
trail_name varchar(100),
trail_type text,
starting_trailhead varchar(100),
ending_trailhead varchar(100),
roundtrip_distance varchar(20),
wilderness_area varchar(100),
trip_description varchar(500),
nearest_town varchar(40),
state text,
country text,
timezone text,
trip_start_hour integer,
trip_start_date integer,
trip_start_month integer,
trip_start_year integer,
trip_end_hour integer,
trip_end_date integer,
trip_end_month integer,
trip_end_year integer,
alert_contact_name varchar(50),
user_contact_relationship varchar(50),
alert_contact_number varchar(11),
alert_contact_email varchar(50),
FOREIGN KEY (alert_id) REFERENCES backpact_user (id)
)